config/routes.rb
Rails.application.routes.draw do

  get 'members/meet' => 'members#meet'
  post 'members/fight' => 'members#fight'
  resources :members

  get '/about' => 'pages#about'
  get '/ranking' => 'members#index'

  root 'members#meet'

end

app/models/member.rb
require 'open-uri'

class Member < ActiveRecord::Base
  def self.random(count)
    Member.where('url is not null').order('random()').limit(count)
  end

  def self.import_from_api(url)
    json = JSON(open(url).read)
    json.each do |m|
      first_name = m['first_name']
      family_name = m['familly_name']
      url = m['hp']
      Member.create(:first_name => first_name, :family_name => family_name, :url => url)
    end
  end

  def self.fight(opts)
    raise unless opts[:winner] and opts[:loser]
    _winner = opts[:winner]
    _loser = opts[:loser]

    winner = Elo::Player.new(:rating => _winner.rating)
    loser = Elo::Player.new(:rating => _loser.rating)
    
    game = winner.versus(loser)
    game.winner = winner
    
    _winner.update(:rating => winner.rating)
    _loser.update(:rating => loser.rating)
  end

  def name
    self.family_name + self.first_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.order('rating desc')
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  ## GET /members/new
  #def new
  #  @member = Member.new
  #end

  ## GET /members/1/edit
  #def edit
  #end

  ## POST /members
  ## POST /members.json
  #def create
  #  @member = Member.new(member_params)

  #  respond_to do |format|
  #    if @member.save
  #      format.html { redirect_to @member, notice: 'Member was successfully created.' }
  #      format.json { render :show, status: :created, location: @member }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @member.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  ## PATCH/PUT /members/1
  ## PATCH/PUT /members/1.json
  #def update
  #  respond_to do |format|
  #    if @member.update(member_params)
  #      format.html { redirect_to @member, notice: 'Member was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @member }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @member.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  ## DELETE /members/1
  ## DELETE /members/1.json
  #def destroy
  #  @member.destroy
  #  respond_to do |format|
  #    format.html { redirect_to members_url }
  #    format.json { head :no_content }
  #  end
  #end

  # GET /members/meet
  def meet
    @left, @right = Member.random(2)
  end

  # POST /members/fight
  def fight
    winner = Member.find(params[:winner_id])
    loser = Member.find(params[:loser_id])
    Member.fight(:winner => winner, :loser => loser)
    respond_to do |format|
      format.html { redirect_to '/' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :family_name, :url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def screenshot_url(page_url)
    "https://api.thumbalizr.com/?url=#{page_url}&width=640&api_key=34UHgDjNTRh2LVG8oRWtAP19mh0D"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Jdmash
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/members/_form.html.haml
= form_for(@member) do |f|
  - if @member.errors.any?
    #error_explanation
      %h2
        = pluralize(@member.errors.count, "error")
        prohibited this member from being saved:
      %ul
        - @member.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :first_name
    %br/
    = f.text_field :first_name
  .field
    = f.label :familly_name
    %br/
    = f.text_field :familly_name
  .field
    = f.label :url
    %br/
    = f.text_field :url
  .actions
    = f.submit

app/views/members/edit.html.haml
%h1 Editing member
= render 'form'
= link_to 'Show', @member
|
\#{link_to 'Back', members_path}

app/views/members/index.html.haml
#ranking.common
  %h1 JDMash
  %p
    %a{:href => '/'} トップページに戻る
  %h2 ランキング
  %table
    %thead
      %tr
        %th Name
        %th Url
        %th Score
    %tbody
      - @members.each do |member|
        %tr
          %td= member.name
          %td
            = link_to member.url, member.url, {:target => '_blank'}
          %td= member.rating
  %p
    %a{:href => '/'} トップページに戻る

app/views/members/meet.html.haml
#wrap
  %p#prompt よいと思ったほうをクリック！！！  
  #wrap-screenshots
    .screenshot.left
      = form_tag '/members/fight' do
        = hidden_field_tag 'winner_id', @left.id
        = hidden_field_tag 'loser_id', @right.id
        = image_submit_tag screenshot_url(@left.url)
    .screenshot.right
      = form_tag '/members/fight' do
        = hidden_field_tag 'winner_id', @right.id
        = hidden_field_tag 'loser_id', @left.id
        = image_submit_tag screenshot_url(@right.url)
  .clear
  %p#next
    %a{:href => '/'} どっちもダメ！次へ！！
#footer
  %p.left
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="国会議員のウェブサイトのランキングをつくろう！" data-lang="ja" data-hashtags="jdmash">ツイート</a>
    <script src="//platform.twitter.com/widgets.js"></script>
  %p.left= link_to 'サイトの説明', '/about'
  %p.left= link_to 'ランキングを見る', '/ranking'
  %p.right
    Powered by
    %a{:href => 'https://japandietdb.net/', :target => '_blank'} 国会DB

app/views/members/new.html.haml
%h1 New member
= render 'form'
= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice
%p
  %strong First name:
  = @member.first_name
%p
  %strong Family name:
  = @member.family_name
%p
  %strong Url:
  = @member.url
= link_to 'Edit', edit_member_path(@member)
|
\#{link_to 'Back', members_path}

app/views/pages/about.html.haml
#about.common
  %h1 JDMash
  
  %p みんなでつくろう国会議員のウェブサイトランキング
  
  %ol
    %li 2名の国会議員のウェブサイトのキャプチャが表示されるので、よいと思ったほうを選びます
    %li 選ばれたほうの点数が上がり、選ばれなかったほうの点数が下がります
    %li 選び続けていると国会議員のウェブサイトのランキングができあがります

  %h2 評価のヒント
  %ul
    %li 基本的にフィーリング. 難しいことは考えずに気に入ったほうをクリック！
    %li 画像がぼこっと欠けているように見えるのはおそらくFlash. iPadなどで閲覧できないサイトということだ

  %h2 データについて
  %p 国会DB APIからインポートした議員のWebサイト一覧を使用しています

  %h2 ソースコード
  %p
    %a{:href => 'https://github.com/miminashi/jdmash', :target => '_blank'} https://github.com/miminashi/jdmash

  %p.to-toppage
    %a{:href => '/'} トップページに戻る